### ISSUE TITLE
version mismatch error

### ISSUE THREAD

**Issue by orthodoc** [subzerocloud/subzero-cli#14]
When running a cloned copy of the postgrest-starter-kit, get this error when running

`subzero migrations init`

error is: `server version: 9.6.5 pg_dumpall version: 9.5.8`
error message is: `aborting because of server version mismatch`

subzero version: 0.1.8 
Native postgresql: 9.5.8 psql: 9.5.8

Mismatch between native postgresql client and postgresql server bundled in the container may cause subzero cli to abort!!

**Comment by ruslantalpa** [comment]
Not sure if this can be considered a subzero-cli bug. It uses the software installed on your host. The solution to this is to either use an older docker image of postgres in the starter kit or upgrade your local postgres client

But porobably the cli could make a few cersion checks and fail more gracefully

**Comment by ruslantalpa** [comment]
thanks for the report, i'll think if it is possible to use the pgdump from inside the container so that there is no chance for this happening.

**Comment by ruslantalpa** [comment]
reopening to remember and fix this

**Comment by ruslantalpa** [comment]
i think this was fixed some time ago.
thank you for the feedback
