### ISSUE TITLE
Integrate with other graphql tools

### ISSUE THREAD

**Issue by itaied246** [subzerocloud/subzero-cli#33]
Is it possible to use this cli (specifically the migrations feature) without the `postgrest` stack?

I want to try `postgraphile`, what are the steps I need to take in order to clean the `subzero` boilerplate and use the migrations feature?

**Comment by ruslantalpa** [comment]
it should be possible to use the migration commands without postgrest since I think they only depend on the database but there is no specific support for other types of stacks
