### ISSUE TITLE
docker containers do not run on raspberry pi

### ISSUE THREAD

**Issue by michi-zuri** [subzerocloud/subzero-cli#52]
Dear Ruslan Talpă

I am stuck with an old Macbook, that doesn't have hypervisor support, so I can't run docker on it. I do have a raspberry Pi server humming along in my home though, doing all kinds of cool things. Docker runs just fine on it, being a recent Linux machine. There's just one catch: the containers need to be compiled for arm architecture. 

My wish would be for subzero to provide arm compatible containers. I have no idea how much effort this would be. Maybe it would be a good exercise for the upcoming shift to Apple ARM for Macbooks and co.? 

Here's an example of some containers being offered in multiple architectures: https://hub.docker.com/r/pihole/pihole/tags  

All the best
Michi

**Comment by ruslantalpa** [comment]
Hey Michi

I don't have an arm test the images + i am in the middle of a lot of stuff with subzero, however, it's a good idea/feature so if you can make a PR to this repo (modify Dockerfile and .circleci/config.yml) i can merge it.
There seems to be a specific tutorial for circleci (which i use for all my tools) and this https://www.docker.com/blog/multi-arch-build-what-about-circleci/

**Comment by michi-zuri** [comment]
Cool! I'll have a go at it, but since I've never used Docker until now, it may take a while until I get it working.
